In [19]:
import pandas as pd
import numpy as np

In [20]:
df= pd.read_csv("dataset_ventes_30_lignes.csv")
df

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client
0,1,2025-08-01,Laptop,Électronique,2,800,1600,Kinshasa,Alice
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob
2,3,2025-08-03,Chaussures,Mode,10,70,700,Kinshasa,Clara
3,4,2025-08-04,T-shirt,Mode,15,25,375,Goma,Daniel
4,5,2025-08-05,Sac à dos,Accessoires,8,60,480,Lubumbashi,Eva
5,6,2025-08-06,Écouteurs,Électronique,12,35,420,Kinshasa,Frank
6,7,2025-08-07,Montre,Accessoires,6,120,720,Bukavu,Grace
7,8,2025-08-08,Chargeur,Électronique,20,15,300,Kananga,Henry
8,9,2025-08-09,Tablette,Électronique,4,300,1200,Kolwezi,Irene
9,10,2025-08-10,Jean,Mode,7,55,385,Kinshasa,John
10,11,2025-08-11,Casquette,Mode,12,20,240,Lubumbashi,Kevin
11,12,2025-08-12,Chaussures,Mode,5,85,425,Goma,Laura
12,13,2025-08-13,Sac à main,Accessoires,6,75,450,Bukavu,Mike
13,14,2025-08-14,Clavier,Électronique,9,40,360,Kinshasa,Nathalie
14,15,2025-08-15,Souris,Électronique,14,22,308,Kananga,Oscar
15,16,2025-08-16,Pantalon,Mode,8,45,360,Kolwezi,Paul
16,17,2025-08-17,Ceinture,Accessoires,10,30,300,Lubumbashi,Rachel
17,18,2025-08-18,Enceinte Bluetooth,Électronique,7,65,455,Kinshasa,Samuel
18,19,2025-08-19,Powerbank,Électronique,11,50,550,Goma,Sarah
19,20,2025-08-20,Sweatshirt,Mode,6,80,480,Bukavu,Thomas
20,21,2025-08-21,Lunettes,Accessoires,9,45,405,Kinshasa,Ursula
21,22,2025-08-22,Webcam,Électronique,5,70,350,Lubumbashi,Victor
22,23,2025-08-23,Chemise,Mode,10,40,400,Kananga,Wendy
23,24,2025-08-24,Sac de voyage,Accessoires,4,110,440,Kolwezi,Xavier
24,25,2025-08-25,Disque SSD,Électronique,6,95,570,Kinshasa,Yvette
25,26,2025-08-26,Pull,Mode,8,65,520,Goma,Zacharie
26,27,2025-08-27,Portefeuille,Accessoires,13,35,455,Lubumbashi,Aline
27,28,2025-08-28,Smartwatch,Électronique,3,180,540,Bukavu,Bruno
28,29,2025-08-29,Robe,Mode,7,90,630,Kinshasa,Chantal
29,30,2025-08-30,Microphone,Électronique,4,125,500,Goma,David

1. Afficher les 10 premières lignes et vérifier le nombre de lignes et de colonnes.

In [21]:
df.head(10)

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client
0,1,2025-08-01,Laptop,Électronique,2,800,1600,Kinshasa,Alice
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob
2,3,2025-08-03,Chaussures,Mode,10,70,700,Kinshasa,Clara
3,4,2025-08-04,T-shirt,Mode,15,25,375,Goma,Daniel
4,5,2025-08-05,Sac à dos,Accessoires,8,60,480,Lubumbashi,Eva
5,6,2025-08-06,Écouteurs,Électronique,12,35,420,Kinshasa,Frank
6,7,2025-08-07,Montre,Accessoires,6,120,720,Bukavu,Grace
7,8,2025-08-08,Chargeur,Électronique,20,15,300,Kananga,Henry
8,9,2025-08-09,Tablette,Électronique,4,300,1200,Kolwezi,Irene
9,10,2025-08-10,Jean,Mode,7,55,385,Kinshasa,John

In [22]:
df.shape

(30, 9)

2. Afficher les colonnes Produit, Quantité, Revenu_USD et Région.

In [23]:
Liste = df[["Produit", "Quantité", "Revenu_USD", "Région"]]
Liste

               Produit  Quantité  Revenu_USD      Région
0               Laptop         2        1600    Kinshasa
1           Smartphone         5        2250  Lubumbashi
2           Chaussures        10         700    Kinshasa
3              T-shirt        15         375        Goma
4            Sac à dos         8         480  Lubumbashi
5            Écouteurs        12         420    Kinshasa
6               Montre         6         720      Bukavu
7             Chargeur        20         300     Kananga
8             Tablette         4        1200     Kolwezi
9                 Jean         7         385    Kinshasa
10           Casquette        12         240  Lubumbashi
11          Chaussures         5         425        Goma
12          Sac à main         6         450      Bukavu
13             Clavier         9         360    Kinshasa
14              Souris        14         308     Kananga
15            Pantalon         8         360     Kolwezi
16            Ceinture        10         300  Lubumbashi
17  Enceinte Bluetooth         7         455    Kinshasa
18           Powerbank        11         550        Goma
19          Sweatshirt         6         480      Bukavu
20            Lunettes         9         405    Kinshasa
21              Webcam         5         350  Lubumbashi
22             Chemise        10         400     Kananga
23       Sac de voyage         4         440     Kolwezi
24          Disque SSD         6         570    Kinshasa
25                Pull         8         520        Goma
26        Portefeuille        13         455  Lubumbashi
27          Smartwatch         3         540      Bukavu
28                Robe         7         630    Kinshasa
29          Microphone         4         500        Goma

3. Afficher les ventes réalisées à Kinshasa.

In [24]:
ventes = Liste[Liste["Région"]=="Kinshasa"]
ventes

               Produit  Quantité  Revenu_USD    Région
0               Laptop         2        1600  Kinshasa
2           Chaussures        10         700  Kinshasa
5            Écouteurs        12         420  Kinshasa
9                 Jean         7         385  Kinshasa
13             Clavier         9         360  Kinshasa
17  Enceinte Bluetooth         7         455  Kinshasa
20            Lunettes         9         405  Kinshasa
24          Disque SSD         6         570  Kinshasa
28                Robe         7         630  Kinshasa

4. Afficher les ventes dont le revenu est supérieur à 500 USD.

In [25]:
ventes=Liste[Liste["Revenu_USD"]>500]
ventes

       Produit  Quantité  Revenu_USD      Région
0       Laptop         2        1600    Kinshasa
1   Smartphone         5        2250  Lubumbashi
2   Chaussures        10         700    Kinshasa
6       Montre         6         720      Bukavu
8     Tablette         4        1200     Kolwezi
18   Powerbank        11         550        Goma
24  Disque SSD         6         570    Kinshasa
25        Pull         8         520        Goma
27  Smartwatch         3         540      Bukavu
28        Robe         7         630    Kinshasa

In [12]:
print(Liste.columns.tolist())

['Produit', 'Quantité', 'Revenu_USD', 'Région']

5. Afficher les ventes de la catégorie Électronique avec une quantité supérieure ou égale à 5.

In [26]:
ventes = df[(df["Catégorie"] == "Électronique") & (df["Quantité"] >= 5)]
ventes

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob
5,6,2025-08-06,Écouteurs,Électronique,12,35,420,Kinshasa,Frank
7,8,2025-08-08,Chargeur,Électronique,20,15,300,Kananga,Henry
13,14,2025-08-14,Clavier,Électronique,9,40,360,Kinshasa,Nathalie
14,15,2025-08-15,Souris,Électronique,14,22,308,Kananga,Oscar
17,18,2025-08-18,Enceinte Bluetooth,Électronique,7,65,455,Kinshasa,Samuel
18,19,2025-08-19,Powerbank,Électronique,11,50,550,Goma,Sarah
21,22,2025-08-22,Webcam,Électronique,5,70,350,Lubumbashi,Victor
24,25,2025-08-25,Disque SSD,Électronique,6,95,570,Kinshasa,Yvette

6. Calculer le revenu total de toutes les ventes.

In [27]:
revenu = df["Revenu_USD"].sum()
print("le revenu total est :", revenu)

le revenu total est : 17168

7. Calculer la quantité totale vendue.

In [28]:
quantite = df["Quantité"].sum()
print("la quantité total vvendue est :", quantite)

la quantité total vvendue est : 246

8. Calculer le revenu moyen par vente.

In [29]:
revenu_moyen = df["Revenu_USD"].mean()
print("revenu moyen par ventes est ", revenu_moyen)

revenu moyen par ventes est  572.2666666666667

9. Trier les ventes du revenu le plus élevé au plus faible.

In [33]:
ventes_triées = df.sort_values(by="Revenu_USD", ascending=False)
ventes_triées

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob
0,1,2025-08-01,Laptop,Électronique,2,800,1600,Kinshasa,Alice
8,9,2025-08-09,Tablette,Électronique,4,300,1200,Kolwezi,Irene
6,7,2025-08-07,Montre,Accessoires,6,120,720,Bukavu,Grace
2,3,2025-08-03,Chaussures,Mode,10,70,700,Kinshasa,Clara
28,29,2025-08-29,Robe,Mode,7,90,630,Kinshasa,Chantal
24,25,2025-08-25,Disque SSD,Électronique,6,95,570,Kinshasa,Yvette
18,19,2025-08-19,Powerbank,Électronique,11,50,550,Goma,Sarah
27,28,2025-08-28,Smartwatch,Électronique,3,180,540,Bukavu,Bruno
25,26,2025-08-26,Pull,Mode,8,65,520,Goma,Zacharie
29,30,2025-08-30,Microphone,Électronique,4,125,500,Goma,David
19,20,2025-08-20,Sweatshirt,Mode,6,80,480,Bukavu,Thomas
4,5,2025-08-05,Sac à dos,Accessoires,8,60,480,Lubumbashi,Eva
17,18,2025-08-18,Enceinte Bluetooth,Électronique,7,65,455,Kinshasa,Samuel
26,27,2025-08-27,Portefeuille,Accessoires,13,35,455,Lubumbashi,Aline
12,13,2025-08-13,Sac à main,Accessoires,6,75,450,Bukavu,Mike
23,24,2025-08-24,Sac de voyage,Accessoires,4,110,440,Kolwezi,Xavier
11,12,2025-08-12,Chaussures,Mode,5,85,425,Goma,Laura
5,6,2025-08-06,Écouteurs,Électronique,12,35,420,Kinshasa,Frank
20,21,2025-08-21,Lunettes,Accessoires,9,45,405,Kinshasa,Ursula
22,23,2025-08-23,Chemise,Mode,10,40,400,Kananga,Wendy
9,10,2025-08-10,Jean,Mode,7,55,385,Kinshasa,John
3,4,2025-08-04,T-shirt,Mode,15,25,375,Goma,Daniel
15,16,2025-08-16,Pantalon,Mode,8,45,360,Kolwezi,Paul
13,14,2025-08-14,Clavier,Électronique,9,40,360,Kinshasa,Nathalie
21,22,2025-08-22,Webcam,Électronique,5,70,350,Lubumbashi,Victor
14,15,2025-08-15,Souris,Électronique,14,22,308,Kananga,Oscar
7,8,2025-08-08,Chargeur,Électronique,20,15,300,Kananga,Henry
16,17,2025-08-17,Ceinture,Accessoires,10,30,300,Lubumbashi,Rachel
10,11,2025-08-11,Casquette,Mode,12,20,240,Lubumbashi,Kevin

10. Trouver le produit ayant généré le revenu le plus élevé sur une seule vente.

In [41]:
produit_revenu_max = df.loc[df["Revenu_USD"].idxmax()]
produit_revenu_max

ID                              2
Date                   2025-08-02
Produit                Smartphone
Catégorie            Électronique
Quantité                        5
Prix_unitaire_USD             450
Revenu_USD                   2250
Région                 Lubumbashi
Client                        Bob
Name: 1, dtype: object

In [45]:
produit_revenu_max = df.nlargest(1, "Revenu_USD")
produit_revenu_max

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob

In [46]:
produit_revenu_max = df.nlargest(3, "Revenu_USD")
produit_revenu_max

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob
0,1,2025-08-01,Laptop,Électronique,2,800,1600,Kinshasa,Alice
8,9,2025-08-09,Tablette,Électronique,4,300,1200,Kolwezi,Irene

11. Calculer le revenu total par région.

In [47]:
Revenu_par_region = df.groupby("Région")["Revenu_USD"].sum()
Revenu_par_region

Région
Bukavu        2190
Goma          2370
Kananga       1008
Kinshasa      5525
Kolwezi       2000
Lubumbashi    4075
Name: Revenu_USD, dtype: int64

12. Calculer la quantité totale vendue par catégorie.
\\\

In [52]:
quantite_totale_par_categorie = df.groupby("Catégorie")["Quantité"].sum()
quantite_totale_par_categorie

Catégorie
Accessoires      56
Mode             88
Électronique    102
Name: Quantité, dtype: int64

13. Calculer le revenu moyen par catégorie.

In [53]:
revenu_moyen_categorie = df.groupby("Catégorie")["Revenu_USD"].mean()
revenu_moyen_categorie

Catégorie
Accessoires     464.285714
Mode            451.500000
Électronique    723.307692
Name: Revenu_USD, dtype: float64

14. Pour chaque région, calculer le revenu total, le revenu moyen et la quantité totale.

In [55]:
# Calcul des agrégations par région
analyse_regions = df.groupby("Région").agg(
    Revenu_Total=("Revenu_USD", "sum"),
    Revenu_Moyen=("Revenu_USD", "mean"),
    Quantité_Totale=("Quantité", "sum")
).reset_index()

analyse_regions

       Région  Revenu_Total  Revenu_Moyen  Quantité_Totale
0      Bukavu          2190    547.500000               21
1        Goma          2370    474.000000               43
2     Kananga          1008    336.000000               44
3    Kinshasa          5525    613.888889               69
4     Kolwezi          2000    666.666667               16
5  Lubumbashi          4075    679.166667               53

15. Calculer le revenu maximum par catégorie.

In [57]:
revenu_max = df.groupby("Catégorie")["Revenu_USD"].max()
revenu_max

Catégorie
Accessoires      720
Mode             700
Électronique    2250
Name: Revenu_USD, dtype: int64

 Créer une colonne Niveau_revenu (Faible / Moyen / Élevé) et compter le nombre de ventes
par niveau.

In [63]:
Niveau_revenu = ["Faible", "Moyen", "Elevé"]

# Utilisation de bins=... et df["Niveau_revenu"] = ...
df["Niveau_revenu"] = pd.cut(
    df["Revenu_USD"],
    bins=[0, 500, 1000, np.inf],
    labels=Niveau_revenu
)
df["Niveau_revenu"].value_counts()

Niveau_revenu
Faible    20
Moyen      7
Elevé      3
Name: count, dtype: int64

In [64]:
df

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client,Niveau_revenu
0,1,2025-08-01,Laptop,Électronique,2,800,1600,Kinshasa,Alice,Elevé
1,2,2025-08-02,Smartphone,Électronique,5,450,2250,Lubumbashi,Bob,Elevé
2,3,2025-08-03,Chaussures,Mode,10,70,700,Kinshasa,Clara,Moyen
3,4,2025-08-04,T-shirt,Mode,15,25,375,Goma,Daniel,Faible
4,5,2025-08-05,Sac à dos,Accessoires,8,60,480,Lubumbashi,Eva,Faible
5,6,2025-08-06,Écouteurs,Électronique,12,35,420,Kinshasa,Frank,Faible
6,7,2025-08-07,Montre,Accessoires,6,120,720,Bukavu,Grace,Moyen
7,8,2025-08-08,Chargeur,Électronique,20,15,300,Kananga,Henry,Faible
8,9,2025-08-09,Tablette,Électronique,4,300,1200,Kolwezi,Irene,Elevé
9,10,2025-08-10,Jean,Mode,7,55,385,Kinshasa,John,Faible
10,11,2025-08-11,Casquette,Mode,12,20,240,Lubumbashi,Kevin,Faible
11,12,2025-08-12,Chaussures,Mode,5,85,425,Goma,Laura,Faible
12,13,2025-08-13,Sac à main,Accessoires,6,75,450,Bukavu,Mike,Faible
13,14,2025-08-14,Clavier,Électronique,9,40,360,Kinshasa,Nathalie,Faible
14,15,2025-08-15,Souris,Électronique,14,22,308,Kananga,Oscar,Faible
15,16,2025-08-16,Pantalon,Mode,8,45,360,Kolwezi,Paul,Faible
16,17,2025-08-17,Ceinture,Accessoires,10,30,300,Lubumbashi,Rachel,Faible
17,18,2025-08-18,Enceinte Bluetooth,Électronique,7,65,455,Kinshasa,Samuel,Faible
18,19,2025-08-19,Powerbank,Électronique,11,50,550,Goma,Sarah,Moyen
19,20,2025-08-20,Sweatshirt,Mode,6,80,480,Bukavu,Thomas,Faible
20,21,2025-08-21,Lunettes,Accessoires,9,45,405,Kinshasa,Ursula,Faible
21,22,2025-08-22,Webcam,Électronique,5,70,350,Lubumbashi,Victor,Faible
22,23,2025-08-23,Chemise,Mode,10,40,400,Kananga,Wendy,Faible
23,24,2025-08-24,Sac de voyage,Accessoires,4,110,440,Kolwezi,Xavier,Faible
24,25,2025-08-25,Disque SSD,Électronique,6,95,570,Kinshasa,Yvette,Moyen
25,26,2025-08-26,Pull,Mode,8,65,520,Goma,Zacharie,Moyen
26,27,2025-08-27,Portefeuille,Accessoires,13,35,455,Lubumbashi,Aline,Faible
27,28,2025-08-28,Smartwatch,Électronique,3,180,540,Bukavu,Bruno,Moyen
28,29,2025-08-29,Robe,Mode,7,90,630,Kinshasa,Chantal,Moyen
29,30,2025-08-30,Microphone,Électronique,4,125,500,Goma,David,Faible

 Créer un tableau croisé dynamique (pivot table) du revenu total par catégorie et par région

In [69]:
pivot_revenu = pd.pivot_table(
    df,
    values="Revenu_USD",
    index="Catégorie",
    columns="Région",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="Total"
)

pivot_revenu

Région        Bukavu  Goma  Kananga  Kinshasa  Kolwezi  Lubumbashi  Total
Catégorie
Accessoires     1170     0        0       405      440        1235   3250
Mode             480  1320      400      1715      360         240   4515
Électronique     540  1050      608      3405     1200        2600   9403
Total           2190  2370     1008      5525     2000        4075  17168

Identifier la région ayant le revenu total le plus élevé pour la catégorie Électronique.

In [72]:
df_electronique = df[df["Catégorie"] == "Électronique"]

revenu_par_region = df_electronique.groupby("Région")["Revenu_USD"].sum()

region_max = revenu_par_region.idxmax()
revenu_max = revenu_par_region.max()

print(f"La région ayant le revenu le plus élevé est : {region_max} avec {revenu_max:,.2f} USD")

La région ayant le revenu le plus élevé est : Kinshasa avec 3,405.00 USD

In [73]:
cols = [c for c in pivot_revenu.columns if c != "Total"]

region_max = pivot_revenu.loc["Électronique", cols].idxmax()
revenu_max = pivot_revenu.loc["Électronique", region_max]

print(f"La région ayant le revenu le plus élevé est : {region_max} avec {revenu_max:,.2f} USD")

La région ayant le revenu le plus élevé est : Kinshasa avec 3,405.00 USD

 Classer les produits selon leur revenu total, du plus élevé au plus faible

In [74]:
classement_produits = df.groupby("Produit")["Revenu_USD"].sum().reset_index()

classement_produits = classement_produits.sort_values(by="Revenu_USD", ascending=False)

classement_produits

               Produit  Revenu_USD
21          Smartphone        2250
9               Laptop        1600
26            Tablette        1200
3           Chaussures        1125
12              Montre         720
17                Robe         630
6           Disque SSD         570
15           Powerbank         550
22          Smartwatch         540
16                Pull         520
11          Microphone         500
19           Sac à dos         480
24          Sweatshirt         480
14        Portefeuille         455
7   Enceinte Bluetooth         455
20          Sac à main         450
18       Sac de voyage         440
28           Écouteurs         420
10            Lunettes         405
4              Chemise         400
8                 Jean         385
25             T-shirt         375
13            Pantalon         360
5              Clavier         360
27              Webcam         350
23              Souris         308
2             Chargeur         300
1             Ceinture         300
0            Casquette         240

 Identifier la région générant le plus de revenus et les produits qui y contribuent le plus.

In [75]:
# 1. Identifier la région générant le plus de revenus
revenu_par_region = df.groupby("Région")["Revenu_USD"].sum()
meilleure_region = revenu_par_region.idxmax()
revenu_max_region = revenu_par_region.max()

print(f"La région la plus rentable est : {meilleure_region} avec un revenu total de {revenu_max_region:,.2f} USD\n")

# 2. Filtrer le DataFrame sur cette meilleure région
df_top_region = df[df["Région"] == meilleure_region]

# 3. Calculer la contribution de chaque produit dans cette région
produits_top_region = (
    df_top_region.groupby("Produit")["Revenu_USD"]
    .sum()
    .reset_index()
    .sort_values(by="Revenu_USD", ascending=False)
)

# 4. Calculer le pourcentage de contribution par rapport au total de la région
produits_top_region["Contribution (%)"] = (
    produits_top_region["Revenu_USD"] / revenu_max_region * 100
).round(2)

# Affichage des meilleurs produits contributeurs
produits_top_region.head(10)

La région la plus rentable est : Kinshasa avec un revenu total de 5,525.00 USD

              Produit  Revenu_USD  Contribution (%)
5              Laptop        1600             28.96
0          Chaussures         700             12.67
7                Robe         630             11.40
2          Disque SSD         570             10.32
3  Enceinte Bluetooth         455              8.24
8           Écouteurs         420              7.60
6            Lunettes         405              7.33
4                Jean         385              6.97
1             Clavier         360              6.52

Afficher les 5 ventes ayant généré le plus faible revenu.

In [76]:
ventes_plus_faibles = df.sort_values(by="Revenu_USD", ascending=True).head(5)
ventes_plus_faibles

,ID,Date,Produit,Catégorie,Quantité,Prix_unitaire_USD,Revenu_USD,Région,Client,Niveau_revenu
10,11,2025-08-11,Casquette,Mode,12,20,240,Lubumbashi,Kevin,Faible
7,8,2025-08-08,Chargeur,Électronique,20,15,300,Kananga,Henry,Faible
16,17,2025-08-17,Ceinture,Accessoires,10,30,300,Lubumbashi,Rachel,Faible
14,15,2025-08-15,Souris,Électronique,14,22,308,Kananga,Oscar,Faible
21,22,2025-08-22,Webcam,Électronique,5,70,350,Lubumbashi,Victor,Faible

Calculer le nombre de ventes par catégorie.

In [77]:
nb_ventes_par_categorie = df["Catégorie"].value_counts()
nb_ventes_par_categorie

Catégorie
Électronique    13
Mode            10
Accessoires      7
Name: count, dtype: int64

 Calculer le pourcentage que représente chaque catégorie dans le revenu total.

In [78]:
# 1. Somme des revenus par catégorie
revenu_par_categorie = df.groupby("Catégorie")["Revenu_USD"].sum().reset_index()

# 2. Calcul du pourcentage du revenu total
revenu_total_global = df["Revenu_USD"].sum()
revenu_par_categorie["Pourcentage_CA (%)"] = (
    (revenu_par_categorie["Revenu_USD"] / revenu_total_global) * 100
).round(2)

# 3. Trier du plus grand pourcentage au plus petit
revenu_par_categorie = revenu_par_categorie.sort_values(by="Pourcentage_CA (%)", ascending=False)

revenu_par_categorie

      Catégorie  Revenu_USD  Pourcentage_CA (%)
2  Électronique        9403               54.77
1          Mode        4515               26.30
0   Accessoires        3250               18.93

 Identifier le produit le plus vendu en quantité, toutes régions confondues.

In [79]:
# 1. Somme des quantités par produit
quantite_par_produit = df.groupby("Produit")["Quantité"].sum().reset_index()

# 2. Extraire le produit ayant la plus grande quantité
produit_top_quantite = quantite_par_produit.nlargest(1, "Quantité")

produit_top_quantite

    Produit  Quantité
2  Chargeur        20

 Calculer l'écart-type du revenu par vente pour évaluer la dispersion des ventes.

In [80]:
# 1. Calcul de l'écart-type global
ecart_type_revenu = df["Revenu_USD"].std()
revenu_moyen = df["Revenu_USD"].mean()
revenu_median = df["Revenu_USD"].median()

# 2. Coefficient de variation (dispersion relative)
coef_variation = (ecart_type_revenu / revenu_moyen) * 100

print(f"Écart-type du revenu : {ecart_type_revenu:,.2f} USD")
print(f"Revenu moyen : {revenu_moyen:,.2f} USD")
print(f"Revenu médian : {revenu_median:,.2f} USD")
print(f"Coefficient de variation : {coef_variation:.2f}%")

Écart-type du revenu : 416.78 USD
Revenu moyen : 572.27 USD
Revenu médian : 452.50 USD
Coefficient de variation : 72.83%

 Créer une colonne Revenu_unitaire (Revenu_USD / Quantité) et afficher les 5 produits ayant
la valeur unitaire la plus élevée

In [81]:
# 1. Création de la colonne Revenu_unitaire
df["Revenu_unitaire"] = df["Revenu_USD"] / df["Quantité"]

# 2. Calcul du revenu unitaire moyen par produit et sélection du Top 5
top_5_unitaire = (
    df.groupby("Produit")["Revenu_unitaire"]
    .mean()
    .reset_index()
    .sort_values(by="Revenu_unitaire", ascending=False)
    .head(5)
)

# 3. Arrondir le résultat pour plus de lisibilité
top_5_unitaire["Revenu_unitaire"] = top_5_unitaire["Revenu_unitaire"].round(2)

top_5_unitaire

       Produit  Revenu_unitaire
9       Laptop            800.0
21  Smartphone            450.0
26    Tablette            300.0
22  Smartwatch            180.0
11  Microphone            125.0

 Comparer le revenu moyen entre Kinshasa et Lubumbashi et indiquer laquelle des deux
régions performe le mieux.

In [82]:
# 1. Filtrer les données pour Kinshasa et Lubumbashi
df_villes = df[df["Région"].isin(["Kinshasa", "Lubumbashi"])]

# 2. Calculer le revenu moyen par région
revenu_moyen_villes = df_villes.groupby("Région")["Revenu_USD"].mean()

moyenne_kinshasa = revenu_moyen_villes.get("Kinshasa", 0)
moyenne_lubumbashi = revenu_moyen_villes.get("Lubumbashi", 0)

# 3. Affichage des résultats
print(f"Revenu moyen à Kinshasa : {moyenne_kinshasa:,.2f} USD")
print(f"Revenu moyen à Lubumbashi : {moyenne_lubumbashi:,.2f} USD\n")

# 4. Identification de la région la plus performante
if moyenne_kinshasa > moyenne_lubumbashi:
    ecart = moyenne_kinshasa - moyenne_lubumbashi
    print(f" Kinshasa performe mieux avec un revenu moyen supérieur de {ecart:,.2f} USD.")
elif moyenne_lubumbashi > moyenne_kinshasa:
    ecart = moyenne_lubumbashi - moyenne_kinshasa
    print(f" Lubumbashi performe mieux avec un revenu moyen supérieur de {ecart:,.2f} USD.")
else:
    print("Les deux régions ont exactement le même revenu moyen.")

Revenu moyen à Kinshasa : 613.89 USD
Revenu moyen à Lubumbashi : 679.17 USD

 Lubumbashi performe mieux avec un revenu moyen supérieur de 65.28 USD.

In [83]:
comparatif = (
    df_villes.groupby("Région")["Revenu_USD"]
    .agg(
        Nombre_de_ventes="count",
        Revenu_Total="sum",
        Revenu_Moyen="mean"
    )
    .reset_index()
)

comparatif["Revenu_Moyen"] = comparatif["Revenu_Moyen"].round(2)
comparatif

       Région  Nombre_de_ventes  Revenu_Total  Revenu_Moyen
0    Kinshasa                 9          5525        613.89
1  Lubumbashi                 6          4075        679.17

Identifier la catégorie la plus rentable dans chaque région (revenu total le plus élevé par
région)

In [85]:
idx = df.groupby(["Région", "Catégorie"])["Revenu_USD"].sum().groupby("Région").idxmax()
df_top = df.groupby(["Région", "Catégorie"])["Revenu_USD"].sum().loc[idx].reset_index()

df_top

       Région     Catégorie  Revenu_USD
0      Bukavu   Accessoires        1170
1        Goma          Mode        1320
2     Kananga  Électronique         608
3    Kinshasa  Électronique        3405
4     Kolwezi  Électronique        1200
5  Lubumbashi  Électronique        2600

 Calculer, pour chaque catégorie, la part du revenu total qu'elle représente à Kinshasa
uniquement

In [86]:
# 1. Filtrer les données sur la région Kinshasa
df_kinshasa = df[df["Région"] == "Kinshasa"]

# 2. Calculer le revenu total à Kinshasa (toutes catégories confondues)
revenu_total_kinshasa = df_kinshasa["Revenu_USD"].sum()

# 3. Calculer la somme du revenu par catégorie
part_categories_kinshasa = (
    df_kinshasa.groupby("Catégorie")["Revenu_USD"]
    .sum()
    .reset_index()
)

# 4. Calculer le pourcentage et arrondir à 2 décimales
part_categories_kinshasa["Part_Revenu_Kinshasa (%)"] = (
    (part_categories_kinshasa["Revenu_USD"] / revenu_total_kinshasa) * 100
).round(2)

# 5. Trier par part décroissante
part_categories_kinshasa = part_categories_kinshasa.sort_values(
    by="Part_Revenu_Kinshasa (%)",
    ascending=False
)

# Affichage du résultat
part_categories_kinshasa

      Catégorie  Revenu_USD  Part_Revenu_Kinshasa (%)
2  Électronique        3405                     61.63
1          Mode        1715                     31.04
0   Accessoires         405                      7.33

 Détecter s'il existe des valeurs manquantes ou aberrantes dans le dataset et proposer une
méthode pour les traiter

In [89]:
# Nombre de valeurs manquantes par colonne
valeurs_manquantes = df.isnull().sum()

# Pourcentage de valeurs manquantes par colonne
pourcentage_manquant = (df.isnull().sum() / len(df)) * 100

# Tableau recapitulatif
df_nan = pd.DataFrame({
    'Manquants': valeurs_manquantes,
    'Pourcentage (%)': pourcentage_manquant.round(2)
})
df_nan[df_nan['Manquants'] > 0]

Empty DataFrame
Columns: [Manquants, Pourcentage (%)]
Index: []

In [90]:
# 1. Détection des valeurs négatives ou nulles (incohérences métiers)
incoherences = df[(df["Revenu_USD"] <= 0) | (df["Quantité"] <= 0)]
print(f"Nombre de ventes incohérentes (<= 0) : {len(incoherences)}")

# 2. Détection par la méthode de l'IQR (Écart interquartile) pour Revenu_USD
Q1 = df["Revenu_USD"].quantile(0.25)
Q3 = df["Revenu_USD"].quantile(0.75)
IQR = Q3 - Q1

# Bornes classique pour identifier les outliers
borne_inferieure = Q1 - 1.5 * IQR
borne_superieure = Q3 + 1.5 * IQR

outliers_iqr = df[(df["Revenu_USD"] < borne_inferieure) | (df["Revenu_USD"] > borne_superieure)]
print(f"Nombre d'outliers détectés par la méthode IQR : {len(outliers_iqr)}")

Nombre de ventes incohérentes (<= 0) : 0
Nombre d'outliers détectés par la méthode IQR : 3

In [91]:
df_nan = pd.DataFrame({
    'Manquants': valeurs_manquantes,
    'Pourcentage (%)': pourcentage_manquant.round(2)
})

In [92]:
# Détecter et afficher le tableau des valeurs manquantes
valeurs_manquantes = df.isnull().sum()
pourcentage_manquant = (df.isnull().sum() / len(df)) * 100

df_nan = pd.DataFrame({
    'Manquants': valeurs_manquantes,
    'Pourcentage (%)': pourcentage_manquant.round(2)
})

df_nan

                   Manquants  Pourcentage (%)
ID                         0              0.0
Date                       0              0.0
Produit                    0              0.0
Catégorie                  0              0.0
Quantité                   0              0.0
Prix_unitaire_USD          0              0.0
Revenu_USD                 0              0.0
Région                     0              0.0
Client                     0              0.0
Niveau_revenu              0              0.0
Revenu_unitaire            0              0.0